---
- name: Install JRE
  yum:
    name: java-1.8.0-openjdk
    state: present
- name: Create directory for app
  file:
    path: /opt/carrental
    state: directory
- name: Copy car_rental.jar
  copy:
    src: "{{car_rental_jar}}"
    dest: "{{car_rental_jar_remote}}"
- name: Create new user
  user:
    name: "{{user}}"
    
- name: Copy systemd
  template:
    src: "{{carrental_service}}"
    dest: "{{carrental_service_remote}}"
- name:
  systemd:
    name: "carrental"
    daemon_reload: yes
    state: restarted