---
- name: "install influxdb"
  yum:
    name: "{{influxdb_url}}"
    state: present
- service:
    name: influxdb
    state: restarted
- name: "Create 'metrics' database"
  shell: "curl -i -XPOST http://localhost:8086/query --data-urlencode 'q=CREATE DATABASE metrics'"
- service:
    name: influxdb
    state: restarted